--------------------------------------------
-- Connect to your Oracle Database instance
-- using sqlcl with your DB user credentials
--------------------------------------------

--------------------------------------------
-- Import data using LOAD
--    Load bank accounts directly
--    Load bank transactions into a staging table first
--    (to avoid errors related to the autogenerated transaction ID´s)
-- Adapt the <path> to match the folder where the files are located
--------------------------------------------

set loadformat csv
-- Make sure to have the decimals in the data correctly interpreted
set load locale American America

-- Import data using LOAD
load table bank_accounts BANK_ACCOUNTS.csv
load table bank_txns_temp BANK_TXNS.csv

/* Expected results:

Load data into table GRAPHUSER.BANK_ACCOUNTS
#INFO Number of rows processed: 10.000
#INFO Number of rows in error: 0
#INFO Last row processed in final committed batch: 10.000
SUCCESS: Processed without errors

Load data into table GRAPHUSER.BANK_TXNS_TEMP
#INFO Number of rows processed: 50.000
#INFO Number of rows in error: 0
#INFO Last row processed in final committed batch: 50.000
SUCCESS: Processed without errors

*/

-- Verify transaction data in the staging table
select * from bank_txns_temp fetch first 10 rows only;

-- Copy data from staging table BANK_TXNS_TEMP into BANK_TXNS
insert into bank_txns (from_acct_id, to_acct_id, txn_date, amount, currency)(
    select from_acct_id, to_acct_id, txn_date, amount, currency from bank_txns_temp);

commit;

-- Verify that your data was loaded correctly
select * from bank_accounts fetch first 10 rows only;
select * from bank_txns fetch first 10 rows only;

-- Drop staging table BANK_TXNS_TEMP
drop table bank_txns_temp purge;
